const API = ['localhost','127.0.0.1'].includes(location.hostname) && location.port === '5173' ? `http://${location.hostname}:18768` : '';
let token = localStorage.getItem('session_token') || '';
let events = [], current = null, mediaRecorder = null, chunks = [], timerId = null, startedAt = 0, silenceTimer = null, demoMode = false;
const DEMO_KEY = 'elder_demo_events_v1';
const PHOTO_KEY = 'elder_demo_photos_v1';
const $ = id => document.getElementById(id);
const views = [...document.querySelectorAll('.view')];
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function showView(id){views.forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='recordsView')loadEvents();if(id==='homeView')renderHome()}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
async function health(){try{const r=await fetch(API+'/health');const j=await r.json();if(j.session_token&&j.session_token!==token){token=j.session_token;localStorage.setItem('session_token',j.session_token)}demoMode=false;setModeLabel();return true}catch(e){demoMode=true;setModeLabel();return false}}
function setModeLabel(){const p=$('modePill');if(p)p.innerHTML=demoMode?'<i></i> 演示模式 · 本机保存':'<i></i> 本机记录中'}
function localEvents(){try{return JSON.parse(localStorage.getItem(DEMO_KEY)||'[]')}catch{return[]}}
function saveLocalEvent(text){const e={record_id:crypto.randomUUID(),recorded_at:new Date().toISOString(),raw_text:text,source_kind:'elder',actor_name:'老人',state:'inbox',version:1,local_safety:{danger_detected:false}};const list=[e,...localEvents()];localStorage.setItem(DEMO_KEY,JSON.stringify(list));return e}
async function api(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};if(token)h['X-Session-Token']=token;try{const r=await fetch(API+path,{...opt,headers:h});let j={};try{j=await r.json()}catch{}return {r,j}}catch(e){return {r:{ok:false,status:0},j:{}}}}
function safetyBanner(s){const b=$('dangerBanner');if(!b)return;if(s?.danger_detected){b.innerHTML=`<b>需要及时关注</b><br>${escapeHtml(s.danger_reminder||'记录中出现需要尽快请专业人员判断的描述，请联系当地急救服务或专业人员。')}`;b.classList.remove('hidden')}else b.classList.add('hidden')}
function stateLabel(s){return ({inbox:'已保存，待整理',draft:'整理草稿，待核对',needs_review:'退回待整理',recorded:'已核对记录准确',superseded:'旧版本'})[s]||s}
function dateText(v){return v?new Date(v).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):''}
function renderArchive(){const ebox=$('archiveEvents'),pbox=$('archivePhotos');if(!ebox||!pbox)return;const active=events.filter(e=>e.state!=='superseded');$('archiveEventCount').textContent=active.length;$('archivePhotoCount').textContent=localPhotos().length;ebox.innerHTML=active.length?active.slice(0,3).map(e=>`<button class="recent-item" data-id="${e.record_id}"><span class="date">${dateText(e.recorded_at)} · ${stateLabel(e.state)}</span><p>${escapeHtml(e.raw_text)}</p></button>`).join(''):'<p class="muted">还没有症状记录</p>';ebox.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{showView('recordsView');setTimeout(()=>showDetail(b.dataset.id),80)});const photos=localPhotos();pbox.innerHTML=photos.length?photos.map((x,i)=>`<div class="archive-photo"><img src="${x.url}" alt="资料照片 ${i+1}"><span>本机照片 · 待接入识别</span></div>`).join(''):'<p class="muted">还没有资料照片</p>'}
function localPhotos(){try{return JSON.parse(localStorage.getItem(PHOTO_KEY)||'[]')}catch{return[]}}
function renderHome(){const box=$('homeRecent');if(!box)return;if(!events.length){box.innerHTML='<p class="muted">还没有记录，先说下今天的情况吧。</p>';return}box.innerHTML=events.filter(e=>e.state!=='superseded').slice(0,3).map(e=>`<button class="recent-item" data-id="${e.record_id}"><span class="date">${dateText(e.recorded_at)} · ${stateLabel(e.state)}</span><p>${escapeHtml(e.raw_text)}</p></button>`).join('');box.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{showView('recordsView');setTimeout(()=>showDetail(b.dataset.id),80)})}
function renderList(){const box=$('eventsList');if(!box)return;if(!events.length){box.innerHTML='<p class="muted">还没有记录，先写下第一次情况吧。</p>';return}box.innerHTML='';events.filter(e=>e.state!=='superseded').forEach(e=>{const n=document.importNode($('eventTpl').content,true);n.querySelector('.event-date').textContent=`${dateText(e.recorded_at)} · ${stateLabel(e.state)}`;n.querySelector('.event-raw').textContent=e.raw_text;n.querySelector('.badges').innerHTML=e.local_safety?.danger_detected?'<span class="badge warn">需要关注</span>':'';n.querySelector('.view-btn').onclick=()=>showDetail(e.record_id);box.appendChild(n)})}
async function loadEvents(){const {r,j}=await api('/api/events');if(r.ok){demoMode=false;events=j.events||[]}else{demoMode=true;events=localEvents()}setModeLabel();renderList();renderHome();renderArchive();if(!r.ok&&!events.length&&$('eventsList'))$('eventsList').innerHTML='<p class="muted">还没有记录，先说下今天的情况吧。</p>'}
async function save(){const text=$('rawText').value.trim();if(!text){$('saveStatus').textContent='请先写下发生的情况';$('saveStatus').className='status error';return}const btn=$('saveBtn');btn.disabled=true;btn.textContent='保存中…';const body={raw_text:text,source_kind:'elder',actor_name:'老人'};const x=demoMode?{r:{ok:true},j:{event:saveLocalEvent(text)}}:await api('/api/events',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(body)});btn.disabled=false;btn.textContent='保存这条记录';if(x.r.ok){current=x.j.event;$('saveStatus').textContent=demoMode?'✓ 已保存在本机演示记录':'✓ 原话已保存';$('saveStatus').className='status ok';$('rawText').value='';await loadEvents();setTimeout(()=>{showView('recordsView');showDetail(current.record_id)},300)}else{$('saveStatus').textContent='保存失败，请重试';$('saveStatus').className='status error'}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function detailHtml(e){const draft=e.draft?`<h3>整理草稿（请核对）</h3><div class="raw-box">${escapeHtml(JSON.stringify(e.draft,null,2))}</div>`:'';return `<div class="section-head"><h2>记录详情</h2><button class="view-btn" onclick="closeDetail()">关闭</button></div><div class="event-date">${dateText(e.recorded_at)} · ${stateLabel(e.state)}</div><h3>原话</h3><div class="raw-box">${escapeHtml(e.raw_text)}</div>${e.local_safety?.danger_detected?`<p class="status error">需要及时联系专业人员：${escapeHtml(e.local_safety.danger_reminder||'请尽快咨询专业人员')}</p>`:''}${draft}<div class="actions">${['inbox','needs_review'].includes(e.state)?'<button class="primary" id="organizeBtn">整理记录</button>':''}${e.state==='draft'?'<button class="primary" id="reviewBtn">我核对过了</button>':''}<button class="outline" id="reviseBtn">修订记录</button><button class="outline" id="historyBtn">查看历史</button></div><div id="subview"></div>`}
async function showDetail(id){if(demoMode){current=events.find(e=>e.record_id===id);if(!current)return}else{const {r,j}=await api('/api/events/'+id);if(!r.ok)return;current=j.event;}safetyBanner(current.local_safety);const d=$('detail');d.classList.remove('hidden');d.innerHTML=detailHtml(current);d.scrollIntoView({behavior:'smooth'});if($('organizeBtn'))$('organizeBtn').onclick=()=>organize(current);if($('reviewBtn'))$('reviewBtn').onclick=()=>review(current);$('reviseBtn').onclick=()=>revise(current);$('historyBtn').onclick=()=>historyView(current)}
function closeDetail(){$('detail').classList.add('hidden')}
async function organize(e){const b=$('organizeBtn');b.disabled=true;b.textContent='整理中…';if(demoMode){const next={...e,state:'draft',version:(e.version||1)+1,draft:{summary:'已生成演示整理草稿',source:'老人原话',needs_review:true}};events=events.map(x=>x.record_id===e.record_id?next:x);localStorage.setItem(DEMO_KEY,JSON.stringify(events));current=next;toast('整理完成，请核对');await loadEvents();showDetail(current.record_id);return}const x=await api('/api/events/'+e.record_id+'/organize',{method:'POST',body:JSON.stringify({expected_version:e.version})});if(x.j.event)current=x.j.event;if(x.r.status===422)toast('原话已保存，整理暂时失败');else if(x.r.ok)toast('整理完成，请核对');else toast('整理失败，请重试');await loadEvents();showDetail(current.record_id)}
async function review(e){if(demoMode){const next={...e,state:'recorded',version:(e.version||1)+1};events=events.map(x=>x.record_id===e.record_id?next:x);localStorage.setItem(DEMO_KEY,JSON.stringify(events));toast('已记录“核对准确”');await loadEvents();showDetail(e.record_id);return}const x=await api('/api/events/'+e.record_id+'/review',{method:'POST',body:JSON.stringify({expected_version:e.version,action:'confirm',note:'仅确认记录准确'})});if(x.r.ok){toast('已记录“核对准确”');await loadEvents();showDetail(e.record_id)}else toast('记录已有新版本，请刷新后再试')}
function revise(e){$('subview').innerHTML=`<h3>修订记录</h3><textarea id="revText" rows="4">${escapeHtml(e.raw_text)}</textarea><input id="revReason" placeholder="修订原因（必填）" class="time-label"><button class="primary" id="submitRev">保存修订</button>`;$('submitRev').onclick=async()=>{const raw=$('revText').value.trim(),reason=$('revReason').value.trim();if(!raw||!reason){toast('请填写内容和修订原因');return}const x=await api('/api/events/'+e.record_id+'/revise',{method:'POST',body:JSON.stringify({raw_text:raw,source_kind:'elder',actor_name:'老人',expected_version:e.version,reason})});if(x.r.ok){toast('修订已保存');await loadEvents();showDetail(x.j.event.record_id)}else toast('修订失败，请重试')}}
async function historyView(e){if(demoMode){$('subview').innerHTML='<h3>历史记录</h3><div class="history"><div class="history-item"><b>创建记录</b> · v1<br><span class="muted">'+dateText(e.recorded_at)+'</span></div></div>';return}const x=await api('/api/events/'+e.record_id+'/history');if(!x.r.ok)return;$('subview').innerHTML='<h3>历史记录</h3><div class="history">'+(x.j.history||[]).map(h=>`<div class="history-item"><b>${h.action}</b> · v${h.version}<br><span class="muted">${new Date(h.at).toLocaleString('zh-CN')}</span></div>`).join('')+'</div>'}
async function handoff(){const b=$('handoffBtn');b.disabled=true;b.textContent='生成中…';if(demoMode){const h={created_at:new Date().toISOString(),unresolved_count:events.filter(e=>e.state!=='recorded').length,items:events.filter(e=>e.state!=='superseded').map(e=>({recorded_at:e.recorded_at,raw_text:e.raw_text,unresolved:e.state!=='recorded'}))};b.disabled=false;b.textContent='生成就诊交接材料';const box=$('handoff');box.classList.remove('hidden');box.innerHTML=`<div class="section-head"><h2>就诊交接材料</h2><button class="view-btn" onclick="window.print()">打印</button></div><p class="muted">演示材料 · ${h.unresolved_count||0} 项待处理</p>`+(h.items||[]).map(i=>`<div class="handoff-item"><b>${dateText(i.recorded_at)}</b><p>${escapeHtml(i.raw_text)}</p>${i.unresolved?'<span class="badge warn">待专业人员处理</span>':''}</div>`).join('');box.scrollIntoView({behavior:'smooth'});return}const x=await api('/api/handoffs',{method:'POST',body:'{}'});b.disabled=false;b.textContent='生成就诊交接材料';if(!x.r.ok){toast('生成失败');return}const h=x.j.handoff,box=$('handoff');box.classList.remove('hidden');box.innerHTML=`<div class="section-head"><h2>就诊交接材料</h2><button class="view-btn" onclick="window.print()">打印</button></div><p class="muted">生成于 ${dateText(h.created_at)} · ${h.unresolved_count||0} 项待处理</p>`+(h.items||[]).map(i=>`<div class="handoff-item"><b>${dateText(i.recorded_at)}</b><p>${escapeHtml(i.raw_text)}</p>${i.unresolved?'<span class="badge warn">待专业人员处理</span>':''}</div>`).join('');box.scrollIntoView({behavior:'smooth'})}
function updateTimer(){const sec=Math.floor((Date.now()-startedAt)/1000);$('voiceTimer').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function setRecording(on){$('recordBtn').classList.toggle('recording',on);$('recordBtn').querySelector('span').textContent=on?'正在说…':'开始说';$('finishVoiceBtn').disabled=!on;$('wave').classList.toggle('active',on)}
async function startVoice(){if(mediaRecorder?.state==='recording'||$('recordBtn').classList.contains('recording')){if(mediaRecorder?.state==='recording')mediaRecorder.stop();stopVoice('手动暂停');return}chunks=[];startedAt=Date.now();updateTimer();timerId=setInterval(updateTimer,1000);setRecording(true);$('voiceHint').textContent='正在听，请慢慢说';try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>chunks.push(e.data);mediaRecorder.onstop=()=>stream.getTracks().forEach(t=>t.stop());mediaRecorder.start()}catch(e){$('voiceHint').textContent='已进入演示模式，可以继续说；麦克风权限未开启';mediaRecorder=null}clearTimeout(silenceTimer);silenceTimer=setTimeout(()=>{if(mediaRecorder?.state==='recording'||$('recordBtn').classList.contains('recording')){$('voiceHint').textContent='好像停了一会儿';$('silenceNotice').classList.remove('hidden');if(mediaRecorder?.state==='recording')mediaRecorder.pause();setRecording(false)}},12000)}
function stopVoice(reason){clearInterval(timerId);clearTimeout(silenceTimer);if(mediaRecorder?.state==='recording'||mediaRecorder?.state==='paused')mediaRecorder.stop();mediaRecorder=null;setRecording(false);$('voiceHint').textContent=reason||'这一段已暂存';$('silenceNotice').classList.add('hidden')}
$('recordBtn').onclick=startVoice;$('finishVoiceBtn').onclick=()=>{stopVoice('这一段已暂存');toast('录音暂存在本页，等待媒体接口接入')};$('resumeBtn').onclick=()=>{if(mediaRecorder?.state==='paused')mediaRecorder.resume();$('silenceNotice').classList.add('hidden');setRecording(true);$('voiceHint').textContent='继续听，请慢慢说';silenceTimer=setTimeout(()=>{if(mediaRecorder?.state==='recording')mediaRecorder.pause();if($('recordBtn').classList.contains('recording')){setRecording(false);$('silenceNotice').classList.remove('hidden');$('voiceHint').textContent='好像停了一会儿'}},12000)};$('pauseBtn').onclick=()=>{stopVoice('已暂停，可以稍后重新开始')};$('photoInput').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const url=URL.createObjectURL(f);$('photoPreview').innerHTML=`<img src="${url}" alt="刚拍的照片"><p>照片已在本机预览，尚未上传。</p>`;$('photoPreview').classList.remove('hidden');$('savePhotoBtn').classList.remove('hidden');$('savePhotoBtn').onclick=()=>{const list=localPhotos();list.unshift({url,created_at:new Date().toISOString()});localStorage.setItem(PHOTO_KEY,JSON.stringify(list));$('savePhotoBtn').classList.add('hidden');renderArchive();toast('已暂存在我的资料')};};$('saveBtn').onclick=save;$('refreshBtn').onclick=async()=>{await health();await loadEvents();toast('记录已刷新')};$('handoffBtn').onclick=handoff;
health().then(loadEvents);
